export const DEVICES = [
  { group: "Popular Devices", options: [{ label: "Custom", value: "custom" }] },
  {
    group: "Apple (MacBooks)",
    options: [
      { label: 'MacBook Air 13.3"', value: "113" },
      { label: "MacBook Pro", value: "112" },
      { label: 'MacBook Pro 13.3"', value: "113" },
      { label: 'MacBook Pro 16"', value: "113" },
    ],
  },
  {
    group: "Apple (iPads)",
    options: [
      { label: 'iPad 10.2"', value: "132" },
      { label: "iPad Air", value: "132" },
      { label: "iPad Air (2020)", value: "132" },
      { label: "iPad Mini", value: "162" },
      { label: 'iPad Pro 11"', value: "132" },
      { label: 'iPad Pro 12.9"', value: "132" },
    ],
  },
  {
    group: "Apple (iPhones)",
    options: [
      { label: "iPhone 5/5c/5s/SE", value: "163" },
      { label: "iPhone 6/6s/7/8", value: "163" },
      { label: "iPhone 6s/7/8 Plus", value: "134" },
      { label: "iPhone X/XS Max", value: "153" },
      { label: "iPhone XR", value: "163" },
      { label: "iPhone 11", value: "163" },
      { label: "iPhone 11 Pro", value: "153" },
      { label: "iPhone 11 Pro Max", value: "153" },
      { label: "iPhone 12/12 Pro", value: "153" },
      { label: "iPhone 12 mini", value: "159" },
      { label: "iPhone 12 Pro Max", value: "153" },
      { label: "iPhone 13/13 Pro", value: "153" },
      { label: "iPhone 13 mini", value: "159" },
      { label: "iPhone 13 Pro Max", value: "153" },
      { label: "iPhone 14/14 Plus/14 Pro/14 Pro Max", value: "153" },
      { label: "iPhone 15/15 Plus/15 Pro/15 Pro Max", value: "153" },
    ],
  },
  {
    group: "Samsung",
    options: [
      { label: "Galaxy S8", value: "142" },
      { label: "Galaxy S8+", value: "132" },
      { label: "Galaxy S9", value: "142" },
      { label: "Galaxy S9+", value: "151" },
      { label: "Galaxy S10", value: "138" },
      { label: "Galaxy S10+", value: "149" },
      { label: "Galaxy S20", value: "141" },
      { label: "Galaxy S20+", value: "140" },
      { label: "Galaxy S20 Ultra", value: "146" },
      { label: "Galaxy S21 Ultra 5G", value: "137" },
    ],
  },
  {
    group: "Google",
    options: [
      { label: "Pixel", value: "168" },
      { label: "Pixel XL", value: "153" },
      { label: "Pixel 2", value: "168" },
      { label: "Pixel 2 XL", value: "154" },
      { label: "Pixel 3", value: "161" },
      { label: "Pixel 3 XL", value: "149" },
      { label: "Pixel 4", value: "161" },
      { label: "Pixel 4 XL", value: "153" },
      { label: "Pixel 5", value: "157" },
    ],
  },
  {
    group: "Microsoft",
    options: [
      { label: "Surface", value: "148" },
      { label: "Surface Pro 7", value: "134" },
      { label: "Surface Book 3", value: "134" },
    ],
  },
];
