export const DEVICES = [
  { group: "Popular Devices", options: [{ label: "Custom", value: "custom" }] },
  {
    group: "Apple (MacBooks)",
    options: [
      { label: 'MacBook Air 13.3"', value: "113" },
      { label: "MacBook Pro", value: "112" },
      { label: 'MacBook Pro 13.3"', value: "113" },
      { label: 'MacBook Pro 16"', value: "113" },
    ],
  },
  {
    group: "Apple (iPads)",
    options: [
      { label: 'iPad 10.2"', value: "132" },
      { label: "iPad Air (All Gen)", value: "132" },
      { label: "iPad Mini (All Gen)", value: "162" },
      { label: 'iPad Pro 11"', value: "132" },
      { label: 'iPad Pro 12.9" / 13"', value: "132" },
    ],
  },
  {
    group: "Apple (iPhones)",
    options: [
      { label: "iPhone 17 Pro Max / 16 Pro Max", value: "153" },
      { label: "iPhone 17 Pro / 16 Pro", value: "153" },
      { label: "iPhone 17 Air / Slim", value: "153" },
      { label: "iPhone 17 / 16", value: "153" },
      { label: "iPhone 14/15 (Pro/Max/Plus)", value: "153" },
      { label: "iPhone 12/13 mini", value: "159" },
      { label: "iPhone 11 Pro / Pro Max", value: "153" },
      { label: "iPhone 11 / XR", value: "163" },
      { label: "iPhone X / XS Max", value: "153" },
      { label: "iPhone 6s/7/8 Plus", value: "134" },
      { label: "iPhone 6/6s/7/8", value: "163" },
      { label: "iPhone 5/5c/5s/SE", value: "163" },
    ],
  },
  {
    group: "Samsung",
    options: [
      { label: "Galaxy S25/S26 Ultra", value: "148" },
      { label: "Galaxy S25/S26+", value: "136" },
      { label: "Galaxy S25/S26", value: "139" },
      { label: "Galaxy S22/S23/S24 Ultra", value: "148" },
      { label: "Galaxy S22+/S23+/S24+", value: "136" },
      { label: "Galaxy S22/S23/S24", value: "139" },
      { label: "Galaxy S21 Ultra 5G", value: "137" },
      { label: "Galaxy S20 Ultra", value: "146" },
      { label: "Galaxy S20/S20+", value: "141" },
      { label: "Galaxy S10/S10+", value: "138" },
      { label: "Galaxy S9/S9+", value: "142" },
      { label: "Galaxy S8/S8+", value: "142" },
    ],
  },
  {
    group: "Google",
    options: [
      { label: "Pixel 10 Pro & XL", value: "144" },
      { label: "Pixel 10", value: "158" },
      { label: "Pixel 6/7/8/9 Pro & XL", value: "144" },
      { label: "Pixel 6/7/8/9", value: "158" },
      { label: "Pixel 5", value: "157" },
      { label: "Pixel 4/4 XL", value: "161" },
      { label: "Pixel 3/3 XL", value: "161" },
      { label: "Pixel 2/2 XL", value: "168" },
      { label: "Pixel/Pixel XL", value: "168" },
    ],
  },
  {
    group: "Microsoft",
    options: [
      { label: "Surface Pro (All)", value: "134" },
      { label: "Surface Book 3", value: "134" },
      { label: "Surface (Generic)", value: "148" },
    ],
  },
];
